### ISSUE TITLE
Create Idea Component not working

### ISSUE THREAD

**Issue by alexandergriffiths526** [BouwenmetStaal/KarambaIDEA#39]
1. Solution exception:Method not found: 'System.String IdeaStatiCa.Plugin.ConnectionHiddenCheckClient.GetCodeSetupJSON()'.

I have downloaded v 3.0.0.2 and opened the example file shown in the recent Connection Wednesday but I get the following error when running the create connection component.

When I look in the file directory It seems to create the connection file for C7 but not for C12.
![image](https://user-images.githubusercontent.com/86045191/176127076-6c6278b1-4202-4bc5-b75e-ef4c1e1bc1e5.png)
![image](https://user-images.githubusercontent.com/86045191/176127170-a0490e8d-140f-49e3-a36f-409d0c06cded.png)

**Comment by nathanlukeIDEA** [comment]
Hi Alex, 

Please update to the latest version of IDEA StatiCa. 

This error is likely due to the method not being installed in the version of IDEA StatiCa you are running.

The Plugin will automatically detect and open the latest version installed on your computer. 

Cheers
Nathan
