### ISSUE TITLE
Use NuGet for Rhino/Grasshopper references

### ISSUE THREAD

**Issue by pearswj** [BouwenmetStaal/KarambaIDEA#6]
Hey! I just saw https://youtu.be/uOJFbWMFe7k?t=292 and I wanted to suggest using NuGet for the Rhino/Grasshopper references.

We've written about it here: https://developer.rhino3d.com/guides/rhinocommon/using-nuget/

Let me know if you'd like me to submit a pull request!

-- Will Pearson
Robert McNeel & Associates

**Comment by BouwenmetStaal** [comment]
Thanks for your feedback. I have implemented this functionality for the upcoming release.
